name: Title
version: '1.0-SNAPSHOT'
main: dev.makashi.titles.titles.Title
api-version: '1.20'
commands:
  test:
    description: Test command
    usage: /<command>
    aliases: [t]
  bowColorRename1:
    description: Rename bow color
    usage: /<command>
    aliases: [bcr1]
  bowColorRename2:
    description: Rename bow color
    usage: /<command>
    aliases: [bcr2]
  bowColorRename3:
    description: Rename bow color
    usage: /<command>
    aliases: [bcr3]
  bowColorRename4:
    description: Rename bow color
    usage: /<command>
    aliases: [bcr4]
  bowColorRename5:
    description: Rename bow color
    usage: /<command>
    aliases: [bcr5]
  bowColorRename6:
    description: Rename bow color
    usage: /<command>
    aliases: [bcr6]

